Lecture.create(lecture_title:'ガイダンス',lecture_date:'2020-04-23',subject_id:'1')
Lecture.create(lecture_title:'確率変数と確率分布',lecture_date:'2020-04-30',subject_id:'1')
Lecture.create(lecture_title:'ガイダンス',lecture_date:'2020-04-23',subject_id:'2')
Lecture.create(lecture_title:'文献講読（1） ',lecture_date:'2020-04-30',subject_id:'2')
Lecture.create(lecture_title:'ガイダンス',lecture_date:'2020-04-23',subject_id:'3')
Lecture.create(lecture_title:'パーソナリティの問題',lecture_date:'2020-04-30',subject_id:'3')
Lecture.create(lecture_title:'ガイダンス',lecture_date:'2020-04-23',subject_id:'4')
Lecture.create(lecture_title:'論文指導(1) ',lecture_date:'2020-04-30',subject_id:'4')
Subject.create(subject_title:'統計基礎',weekday:'friday',period:'3',teacher_id:'1')
Subject.create(subject_title:'民法特別研究',weekday:'monday',period:'5',teacher_id:'1')
Subject.create(subject_title:'心理学特別研究',weekday:'wednesday',period:'5',teacher_id:'2')
Subject.create(subject_title:'知的財産法特別研究',weekday:'thursday',period:'2',teacher_id:'2')
Teacher.create(name:'山田太郎')
Teacher.create(name:'佐藤真一')